---
  - name: Make sure the LCM refresh mode is disabled
    win_lcm5:
      refresh_mode: "Disabled"
    tags:
      - Config

  - name: Download xActiveDirectory
    win_oneget:
      name: "xActiveDirectory"
    tags:
      - Oneget

  - name: Download xNetworking
    win_oneget:
      name: "xNetworking"
    tags:
      - Oneget

  - name: Install ADDS and RSAT
    win_feature:
      name: "AD-Domain-Services,RSAT-AD-Tools"
    tags:
      - WindowsFeature

  - name: Init Domain
    win_dsc:
      resource_name: xADDomain
      DomainName: "{{ domainname }}"
      DomainNetbiosName: "{{ domainnetbios }}"
      DomainAdministratorCredential_username: "{{ domainadmin_user }}"
      DomainAdministratorCredential_password: "{{ domainadmin_pass }}"
      SafemodeAdministratorPassword_username: "{{ safemodeadmin_user }}"
      SafemodeAdministratorPassword_password: "{{ safemodeadmin_pass }}"
    tags:
      - DomainInit
    notify:
      - Reboot Server

  # wait for all the services to load before adding and promoting users.
  - meta: flush_handlers
  - name: Pause for a min
    pause:
      minutes: 1
